name: Move closed issue
on:
  issues:
    types:
      - closed
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Lexii
          column: Done
          repo-token: ${{ secrets.REPO_TOKEN }}
