name: Move closed issue to Done
on:
  issues:
    types:
      - closed
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Lexii
          column: Done
          repo-token: ${{ secrets.REPO_TOKEN }}
